### ISSUE TITLE
[BUG] le /taille traversée de block

### ISSUE THREAD

**Issue by popolecool** [ServerOpenMC/Plugin#176]
avec /taille quan on est dans un cois est qu'on fait un taille de 200 a 100 vis versa on peux traverser les mur sans problème exemple ![le tail est buger](https://cdn.discordapp.com/attachments/1258441016730718318/1261403903627493448/image.png?ex=6692d56e&is=669183ee&hm=9d825905a2999aa60e4756bea001c04f070073dd0872778e4b77c9586ca3f6c8&  "le bug")
![avec la brochet de dev](https://cdn.discordapp.com/attachments/1258441016730718318/1261403903325372436/image.png?ex=6692d56e&is=669183ee&hm=49ef65f3f5ac318bed6316d2db04daf59d4371f3b572f70dcd5c2e75aab35fdf&)

pour régler le problème il fait quel quand la commande soit exécuter on soit tp au block ou on a fait la commande

**Comment by Xernas78** [comment]
Ça serait bien de détailler un peu

**Comment by popolecool** [comment]
recharge la page j'ai fini de modifier le text, sinon on peux voc

**Comment by MathiasDPX** [comment]
> Ça serait bien de détailler un peu

en augmentant de taille tu noclip à travers les blocs
