### ISSUE TITLE
[bug] récupération des tombe avec de l'eau

### ISSUE THREAD

**Issue by popolecool** [ServerOpenMC/Plugin#243]
il est possible de récupère des tombe avec un s'eau comme c'est un chorus fruit mais avec le texture des tombe 
la tombe a était par @Martinou2x  si possible de fix le problème 
merci désolé  j'ai pas d'image d'illustration

**Comment by Martinou2x** [comment]
Je report ça à itemsadder

**Comment by Dartsgame974** [comment]
J'ai perdu mon stuff en mourant d'eau

**Comment by Martinou2x** [comment]
j'ai mis une sécurité, il peut y avoir des failles, faut attendre qu'itemsadder règle le bug
