### ISSUE TITLE
Les morts dans l'eau : Les tombes dispawnent

### ISSUE THREAD

**Issue by Dartsgame974** [ServerOpenMC/Plugin#286]
Je suis mort et...
https://www.youtube.com/watch?v=6wWQ2QNhQRM

**Comment by Dartsgame974** [comment]
https://youtu.be/6wWQ2QNhQRM

**Comment by Dartsgame974** [comment]
https://youtu.be/hWcL6YEr7Ro

**Comment by Dartsgame974** [comment]
https://youtu.be/hWcL6YEr7Ro

**Comment by Martinou2x** [comment]
c'est corrigé
