### ISSUE TITLE
Mousse et claim

### ISSUE THREAD

**Issue by Dartsgame974** [ServerOpenMC/Plugin#306]
Heu on ne peut plus faire de farm a mousse dans ses propres claims

**Comment by sajiterre** [comment]
Je pense que ses une sécurité pour éviter de transformer ton claim en biome mouse de l'extérieur de ton claim

**Comment by AxenoDev** [comment]
je check ça, ça te dit qu'il y a un claim a proximité ?

**Comment by Dartsgame974** [comment]
oui

**Comment by AxenoDev** [comment]
yep normal je n'avais pas fait de verif si le player était dans le claim, normalement c'est good la
