### ISSUE TITLE
[BUG] Utiliser le baton de claim comme stick dans ls crafts

### ISSUE THREAD

**Issue by ThibaudVall** [ServerOpenMC/Plugin#319]
Il est possible d'utiliser le baton de claim dans les crafts.

Par exemple, si on craft une épée, on peut remplacer le stick par le Baton de claim(obtensible avec le /claim)

**Comment by Armibule** [comment]
Je ne sais pas si c'est aussi problématique que ça

**Comment by llextv** [comment]
C'est good

**Comment by Fnafgameur** [comment]
Dès que j'en aurai fini avec les tombes, je vais voir pour m'occuper de fix certains bugs concernant les teams

**Comment by Martinou2x** [comment]
Comment ça avec les tombes ? C'est moi qui m'en occupe mdr

**Comment by Fnafgameur** [comment]
> Comment ça avec les tombes ? C'est moi qui m'en occupe mdr

J'ai prévenu hier soir que je m'occupais de patch certains problèmes sur les tombes
([https://discord.com/channels/1161296442577653802/1257447563259412611/1270564208240623677](https://discord.com/channels/1161296442577653802/1257447563259412611/1270564208240623677))

**Comment by Martinou2x** [comment]
quels sont les problèmes ?

**Comment by Fnafgameur** [comment]
> quels sont les problèmes ?

La propreté de certains morceaux de code, mais bon ça c'est pas très grave et c'est assez rapide.
Les tombes qui explosent laissent le display text encore présent.
On ne peut pas placer d'eau autour d'une tombe (pour je ne sais quelle raison).
On peut cliquer 1 bloc plus loin pour ouvrir la tombe.
Pas de détection de la hauteur à laquelle la tombe va être placé si le joueur meurt sur un demi-bloc (par exemple s'il meurt 1 bloc avant la couche max sur une dalle, sa tombe n'apparaît pas et le stuff depop (je sais que c'est un scénario très peu probable, mais pas impossible)).
Je n'ai pas encore vérifié, mais je pense que si un joueur meurt dans le vide, sa tombe ne sera pas placé (je pense surtout à l'END pour cette situation).

Tous ces problèmes ont été fix pour le moment (sauf le dernier concernant le vide) et je fais toujours quelques tests afin d'en trouver d'autres.

**Comment by Martinou2x** [comment]
Pour le 1 bloc plus loin j'ai complétement fail car le equals fonctionnait pas.
Pour l'eau à coté de la tombe, faut garder car il y a un bug avec Itemsadder
Pour les demi-blocs ça a était corrigé et testé
Pour le vide, c'est logique

**Comment by Martinou2x** [comment]
ah et pour la propreté, merci de l'avoir fait x)

**Comment by Fnafgameur** [comment]
> Pour le 1 bloc plus loin j'ai complétement fail car le equals fonctionnait pas. Pour l'eau à coté de la tombe, faut garder car il y a un bug avec Itemsadder Pour les demi-blocs ça a était corrigé et testé Pour le vide, c'est logique

- Quel est le bug avec ItemsAdder ?
- Avec ta méthode "isHalfBlock(Block block)" ou qqch comme ça ? Si oui, la méthode n'était pas extrêmement efficace car certains blocks étaient oublié, j'ai plutôt opté pour un système qui check si la coo Y du joueurs est un entier, si oui, on tente de placer la tombe, sinon, on prend l'entier du dessus (ex : Y : 66.2 -> Y : 67).
- Je pense que ça embêterait pas mal de gens qu'il y ait un système de tombe, mais qui ne fait pas en sorte d'au moins placer la tombe 1 bloc au-dessus de la limite pour qu'ils puissent récupérer leurs stuff, de plus, je suis quasi sûr que ça causerai une erreur dans la console.

**Comment by Fnafgameur** [comment]
> 1. Le voici : [Transparent block break with water PluginBugs/Issues-ItemsAdder#3853](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3853)
> 2. Très bonne idée, je n'y avais pas pensé.
> 3. Ouep effectivement

Okay, tu peux m'envoyer une archive contenant les fichiers configs (ainsi que les models 3D et textures) de la tombe pour que je puisse faire des tests de mon côté ?

**Comment by AxenoDev** [comment]
c'est régler le problème du stick

**Comment by Martinou2x** [comment]
Bien sûr ! 
[itemsadder.zip](https://github.com/user-attachments/files/16549720/itemsadder.zip)


> > 1. Le voici : [Transparent block break with water PluginBugs/Issues-ItemsAdder#3853](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3853)
> > 2. Très bonne idée, je n'y avais pas pensé.
> > 3. Ouep effectivement
> 
> Okay, tu peux m'envoyer une archive contenant les fichiers configs (ainsi que les models 3D et textures) de la tombe pour que je puisse faire des tests de mon côté ?
