### ISSUE TITLE
bug main droite main gauche 

### ISSUE THREAD

**Issue by Ricorsse** [ServerOpenMC/Plugin#364]
si on as un outil dans la main gauche il donne son apparence a l item que l on porte dans la main droite par exemple le steak dans la main droite a u l'apparence d une hache si une hache est porter dans la main gauche ![2024-08-10_18 28 45] (https://github.com/user-attachments/assets/1c2b27ae-f908-4f08-be7f-de01b3c249f4)
![2024-08-10_18 28 48](https://github.com/user-attachments/assets/84704d63-8f4c-4c0b-8487-9ccb6051549c)

![2024-08-10_18 27 51](https://github.com/user-attachments/assets/c78f14c6-1660-47a3-ade5-2f7e2995b43d)
![2024-08-10_18 27 56](https://github.com/user-attachments/assets/2c9ce22d-efc8-4c32-9cc2-1ce608ec4d4a)
![2024-08-10_18 28 06](https://github.com/user-attachments/assets/aac57589-6cc8-45c0-b0fa-3bac3f80dfe3)
![2024-08-10_18 28 09](https://github.com/user-attachments/assets/5a76e1ce-248a-4d3d-b50e-c608aeb16ba9)
![2024-08-10_18 28 24](https://github.com/user-attachments/assets/caf9b0f5-4b18-47aa-9359-46fcee459d4d)
![2024-08-10_18 28 26](https://github.com/user-attachments/assets/7a78f2a7-9b54-450f-927a-c8e2b415986d)
![2024-08-10_18 28 39](https://github.com/user-attachments/assets/7aee845e-5e43-48d1-b144-16aa6509b2b2)
![2024-08-10_18 28 43](https://github.com/user-attachments/assets/b1be8681-4b1c-4b06-a33e-b98e1aea8165)

**Comment by sajiterre** [comment]
Sûrement un bug de Item Adder

**Comment by ri1ongithub** [comment]
Probablement un bug coté client (minecraft ou optifine)

**Comment by sajiterre** [comment]
> Probablement un bug coté client (minecraft ou optifine)
>  

Ya pas optifine en 1.21 ;------;

**Comment by sajiterre** [comment]
Mais oui ses sûrement côté client

**Comment by Ricorsse** [comment]
effectivement c'est a cause d optifine

**Comment by sajiterre** [comment]
> effectivement c'est a cause d optifine 
Hein ?

**Comment by sajiterre** [comment]
On a fait pipi dans ta tête ou quoi ?

**Comment by sajiterre** [comment]
Ya aps optifine en 1.21

**Comment by Ricorsse** [comment]
j'ai une version 1.21 d optiofine  preview

**Comment by Ricorsse** [comment]
[preview_OptiFine_1.21.1_HD_K_J3_pre12.zip](https://github.com/user-attachments/files/16570346/preview_OptiFine_1.21.1_HD_K_J3_pre12.zip)
