### ISSUE TITLE
Ajouter un aimant 

### ISSUE THREAD

**Issue by Nocolm** [ServerOpenMC/Plugin#379]
G fais un plug d'aimant pour le serv mais il manque une fonction pour qu'il n'attire pas les items des autre joueur et/ou qu'il se désactivé dans les claims : 

package com.example.magnet;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.entity.Item;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.scheduler.BukkitRunnable;

public class MagnetPlugin extends JavaPlugin {

    @Override
    public void onEnable() {
        new BukkitRunnable() {
            @Override
            public void run() {
                for (Player player : Bukkit.getOnlinePlayers()) {
                    if (player.getInventory().getItemInMainHand().getType() == Material.IRON_INGOT) {
                        attractItems(player);
                    }
                }
            }
        }.runTaskTimer(this, 0L, 10L);
    }

    private void attractItems(Player player) {
        double radius = 5.0;
        for (Item item : player.getWorld().getEntitiesByClass(Item.class)) {
            if (item.getLocation().distance(player.getLocation()) < radius) {
                item.setVelocity(player.getLocation().toVector().subtract(item.getLocation().toVector()).normalize());
            }
        }
    }
}

Et le plugin.yml

name: MagnetPlugin
version: 1.0
main: com.example.magnet.MagnetPlugin
api-version: 1.13

(PS : deso c la première fois que j'utilise github je c pas comment ça marche )

**Comment by ri1ongithub** [comment]
👋

Il faut faire une pr pour contribuer au projet (comme décrit sur le wiki)

_De plus, faire un plugin Minecraft c'est pas juste demander à chatGPT de coder à ta place ou chercher sur internet.

Si tu ne sais pas développer, tu peux toujours proposer ton idée sur le discord dans l'espoir qu'un développeur prenne le temps de développer la feature_
