### ISSUE TITLE
Stack Block Diamond

### ISSUE THREAD

**Issue by LVXN456** [ServerOpenMC/Plugin#386]
Il est très embêtant que a chaque fois que l'on fait un beacon en diamond les blocks se stack surtout que cela n'apporte rien au serveur

**Comment by llextv** [comment]
?

**Comment by llextv** [comment]
pas compris

**Comment by LVXN456** [comment]
quand on pose un block de diamond par terre on peut clicker dessus pour mettre 2 block l'un dans l'autre c comme les mob https://github.com/user-attachments/assets/5f540324-3a40-4a44-bac1-7f928f566651
