### ISSUE TITLE
bug texture  elevator 2 texture diferente selon les etage 

### ISSUE THREAD

**Issue by Ricorsse** [ServerOpenMC/Plugin#407]
![2024-08-29_21 39 21](https://github.com/user-attachments/assets/6d0693c9-3be0-4936-89bf-4e9da152df8f)
![2024-08-29_21 39 30](https://github.com/user-attachments/assets/20188872-8fa3-44ad-b0ad-b1032f791f35)

**Comment by llextv** [comment]
Sa été réglé c'etait un bug du texture pack qui chargait pas au join
fait /iatextures la prochaine fois

**Comment by Ricorsse** [comment]
non non ca n'as pas été régler  malgré le /iatexture  les escalator de notre base ne change pas  il reste buggé
