### ISSUE TITLE
[Bug] On peut obtenir de l'xp à l'infini en cassant une fusée

### ISSUE THREAD

**Issue by MagnetoCraft** [ServerOpenMC/Plugin#420]
On peut casser et reposer une fusée autant de fois qu'on le souhaite et l'on récupère 10 xp à chaque fois qu'on la casse

**Comment by MathiasDPX** [comment]
@ri1ongithub c'est qui qui t'avais prévenu 🤡

**Comment by ri1ongithub** [comment]
Le problème vient pas de moi, et j'avais déjà prévenu qu'il fallait le fix, il faut modif la config du bail d'xp pour enlever les armor stands

**Comment by MathiasDPX** [comment]
fixed
