### ISSUE TITLE
[BUG] Quand on mange une pomme ça nous dis un truc

### ISSUE THREAD

**Issue by AxenoDev** [ServerOpenMC/Plugin#443]
Quand on mange une pomme (Pomme / Golden Apple / ...) ça nous dit: "Votre maison n'est pas accessible !"
![image](https://github.com/user-attachments/assets/38cae817-352b-4bec-877c-dda7d894c0e0)

**Comment by AxenoDev** [comment]
Fin en localhost ça nous dis ça

**Comment by MathiasDPX** [comment]
C'est parceque la perm "ayw.block.dream" est à false par défaut
