### ISSUE TITLE
Mon mail ne s'ouvre pas car il y a trop d'item

### ISSUE THREAD

**Issue by Nocolm** [ServerOpenMC/Plugin#460]
après avoir échanger de la terre cuite émaillé magenta je me suis retrouver avec un mail , jusque là normale , mais en essayant d'ouvrir le mail impossible une erreur apparait et je pense que le problème vient du faite que le mail contient 3456 items. Et aussi l'heure du mail est pas la bonne.
![image](https://github.com/user-attachments/assets/c31a00e4-bf86-4af0-aeb2-56bd5fa1d2ca)

**Comment by Nathgen** [comment]
Tu peut donner un screen quand tu ouvre le mail

**Comment by Nocolm** [comment]
> Tu peut donner un screen quand tu ouvre le mail

le probleme est que le seul moyen de l'ouvrir est depuis l'interface mailbox mais sa ne fait rien mais le message d'erreur que j'ai eu était : " une erreur est survenu lors de l'execution de cette command "

**Comment by Nathgen** [comment]
Mais le problème a été régler après ?

**Comment by Nocolm** [comment]
> Mais le problème a été régler après ?

non j'ai toujours le mail et je ne peux pas clicker dessus

**Comment by Nocolm** [comment]
par contre je peux annuler le mail puisque je reçoit un mail provenant de moi, peut-être cela règlera le problème mais je préfère ne rien tenter

**Comment by Nocolm** [comment]
okay problème régler j'ai récupérer mais objet. merci a Louty_13 qui a eu le même bug et qui m'a dit que je pouvais annuler le mail ^^
