### ISSUE TITLE
Bug des homes

### ISSUE THREAD

**Issue by gab4000** [ServerOpenMC/Plugin#461]
Lorsqu'on supprime un home, il revient lorsqu'on se reconnecte
Donc il ne se supprime pas

**Comment by AxenoDev** [comment]
heuuu, sa ne me le fait pas, tu pourrais donner plus de détaille ?

**Comment by gab4000** [comment]
En gros, j'ai déplacé ma maison a un autre endroit, et j'ai supprimé le home "maison"
Lorsque je me suis reconnecté plus tard, le home était encore présent (pourtant ne l'était plus lors de la deconnexion)
