### ISSUE TITLE
[Bug] On peut dupli tous les items de Itemsadder

### ISSUE THREAD

**Issue by Nocolm** [ServerOpenMC/Plugin#478]
il faut mettre l'item a dupliquer tout en haut a gauche de votre inventaire, aller dans un auto-crafter et faire un shift click et boum l'objet se dédouble et quand on le récupère boum encore un dédoublement

**Comment by iambibi** [comment]
Si tu connais un minimum le plugin, on a rien avoir avec ItemAdder il faut aller sur leur github je crois et dire ce bug a eux

**Comment by MathiasDPX** [comment]
Ouvre une issue sur leur github
